name: CI for tqsdk-python-private

on: [push]

jobs:
  build-win:
    strategy:
      matrix:
        envinfo:
          - { name: 'windows-3.6-x64', os: windows-latest, python-version: 3.8.x, python-arch: x64, bdist-platform: 'win_amd64' }
          - { name: 'windows-3.6-x86', os: windows-latest, python-version: 3.8.x, python-arch: x86, bdist-platform: 'win32' }

    env:
        PYTHONIOENCODING: "utf-8"

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: shinnytech/tqsdk-python-private
        ref: add_cythonize
        token: ${{ secrets.GH_PAT }}

    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Package web
      run: |
        cd ./web/
        yarn install --frozen-lockfile
        yarn run build
      env:
        CI: true

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.envinfo.python-version}}
        architecture: ${{matrix.envinfo.python-arch}}
        
    - name: Install dependencies
      run: |
        git lfs install
        git lfs pull
        python -m pip install --upgrade pip wheel setuptools Cython
        python -m pip install -r requirements.txt
        python -m pip install Sphinx autodocsumm sphinx_rtd_theme jieba

    - name: Build bdist wheel
      shell: bash
      run: |
        rm -rf build
        python setup.py bdist_wheel -p ${{ matrix.envinfo.bdist-platform }}
        ls -lrt

    - name: Upload bdist package
      uses: actions/upload-artifact@v2
      with:
        name: bdist-file
        path: dist/*.whl
